query findAllRestaurantReviews(
  $restaurantName: String!
  $input: ReviewPaginationInput!
) {
  findAllRestaurantReviews(restaurantName: $restaurantName, input: $input) {
    edges {
      node {
        ...ReviewDetails
        restaurant {
          id
          name
        }
      }
    }
  }
}
